---
abstract: 'Returns information about languages.'
author:
  - 'Martin Majlis <martin@majlis.cz>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
  Time::HiRes: 0
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.141170'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-Metadata
requires:
  LWP::Simple: 0
  constant: 0
  strict: 0
  warnings: 0
version: 0.005
